---
language: node_js
node_js: "6"
dist: trusty
sudo: false
install: |
    # Install SpiderMonkey (js/jsshell)
    export TMP=$(mktemp);
    wget https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/jsshell-linux-x86_64.zip -O $TMP;
    mkdir jsshell;
    unzip -d jsshell $TMP;
    rm $TMP;
    unset TMP;
    export PATH=$PATH:$(pwd)/jsshell;

    # Install ChakraCore (ch/ch)
    wget https://s3.amazonaws.com/eshost-builds/ChakraCore-Debug_linux_1_7_0.tar.gz;
    tar -xvf ChakraCore-Debug_linux_1_7_0.tar.gz;
    export PATH=$PATH:$(pwd)/out/Debug;

    which js;
    which ch;

    npm install;

script: npm test
